title: Tim Sabu
logo: /Tim%20Sabu.jpeg?raw=true
description: A professional with wide range experience in Tech, Operations and Business side of things.I consider myself lucky to have developed recommendation systems and other ML models for the startup I was part of. Upskilled myself with an M.S in C.S I felt there was gap in my knowledge.
#show_downloads: true
theme: jekyll-theme-minimal
